const actionTypes = {
	FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
	FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
	UPDATE_GRADE: 'UPDATE_GRADE',
	FETCH_OPTIONS_SUCCESS: 'FETCH_OPTIONS_SUCCESS',
	FETCH_OPTIONS_ERROR: 'FETCH_OPTIONS_ERROR',
	INDIVIDUAL_GRADE_UPDATE: 'INDIVIDUAL_GRADE_UPDATE'
};

export default actionTypes;
